name: Spam Classifier CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_TRACKING_URI: https://dagshub.com/adhavprasanna/spam-classifier.mlflow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python -m src.train

      - name: Run tests
        run: |
          pytest

      - name: Evaluate model promotion
        id: promotion
        run: |
          python -m src.promote_model

      - name: Show promotion result
        run: |
          echo "Model promotion status: ${{ steps.promotion.outputs.promotion_status }}"

      - name: Log in to GitHub Container Registry
        if: steps.promotion.outputs.promotion_status == 'promoted'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        if: steps.promotion.outputs.promotion_status == 'promoted'
        run: |
          docker build -t spam-classifier-api .

      - name: Tag Docker image
        if: steps.promotion.outputs.promotion_status == 'promoted'
        run: |
          docker tag spam-classifier-api ghcr.io/${{ github.repository }}:latest

      - name: Push Docker image
        if: steps.promotion.outputs.promotion_status == 'promoted'
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Skip Docker publishing
        if: steps.promotion.outputs.promotion_status == 'rejected'
        run: |
          echo "Model was rejected."
          echo "Docker image will not be published."